namespace Hibird_Theory_Backend.Models
{
    public class LeonMatrix
    {
        public double v1 { get; set; }
        public double v2 { get; set; }
        public double v3 { get; set; }
        public double v4 { get; set; }
        public double v5 { get; set; }
        public double v6 { get; set; }
        public double v7 { get; set; }
        public double v8 { get; set; }
        public double v9 { get; set; }
        public double v10 { get; set; }
        public double v11 { get; set; }
        public double v12 { get; set; }
        public double v13 { get; set; }
        public double v14 { get; set; }
        public double v15 { get; set; }
        public double v16 { get; set; }
        public double v17 { get; set; }
        public double v18 { get; set; }
        public double v19 { get; set; }
        public double v20 { get; set; }
        public double v21 { get; set; }
        public double v22 { get; set; }
        public double v23 { get; set; }
        public double v24 { get; set; }
        public double v25 { get; set; }
        public double v26 { get; set; }
        public double v27 { get; set; }
        public double v28 { get; set; }
        public double v29 { get; set; }
        public double v30 { get; set; }
        public double v31 { get; set; }
        public double v32 { get; set; }
        public double v33 { get; set; }
        public double v34 { get; set; }
        public double v35 { get; set; }
        public double v36 { get; set; }
        public double v37 { get; set; }
        public double v38 { get; set; }
        public double v39 { get; set; }
        public double v40 { get; set; }
        public double v41 { get; set; }
        public double v42 { get; set; }
        public double v43 { get; set; }
        public double v44 { get; set; }
        public double v45 { get; set; }
        public double v46 { get; set; }
        public double v47 { get; set; }
        public double v48 { get; set; }
        public double v49 { get; set; }
        public double v50 { get; set; }
        public double v51 { get; set; }
        public double v52 { get; set; }
        public double v53 { get; set; }
        public double v54 { get; set; }
        public double v55 { get; set; }
        public double v56 { get; set; }
        public double v57 { get; set; }
        public double v58 { get; set; }
        public double v59 { get; set; }
        public double v60 { get; set; }
        public double v61 { get; set; }
        public double v62 { get; set; }
        public double v63 { get; set; }
        public double v64 { get; set; }
        public double v65 { get; set; }
        public double v66 { get; set; }
        public double v67 { get; set; }
        public double v68 { get; set; }
        public double v69 { get; set; }
        public double v70 { get; set; }
        public double v71 { get; set; }
        public double v72 { get; set; }
        public double v73 { get; set; }
        public double v74 { get; set; }
        public double v75 { get; set; }
        public double v76 { get; set; }
        public double v77 { get; set; }
        public double v78 { get; set; }
        public double v79 { get; set; }
        public double v80 { get; set; }
        public double v81 { get; set; }
        public double v82 { get; set; }
        public double v83 { get; set; }
        public double v84 { get; set; }
        public double v85 { get; set; }
        public double v86 { get; set; }
    }
}